//This is a header file generated by HJReflectionTool automatically using libclang
//any change may be overwritten!

//Reflection data for class "HJTest", inherited from "HJObject"
struct HJTestRegisterHelper_9_16 {
	HJTestRegisterHelper_9_16(){
		const std::vector<ReflectInfo> reflectInfoArray{
			MAKE_REFLECT_INFO(id, int, HJTest),
			MAKE_REFLECT_INFO(name, std::string, HJTest),
			MAKE_REFLECT_INFO(grade, float, HJTest)};
		HJClass::registerClass("HJTest", new HJClass("HJTest",reflectInfoArray,"HJObject",&HJTest::instantiate));
	}
} HJTestRegisterHelper_9_16_Instance;
HJOBJECT_GET_CLASS_INFO(HJTest, HJObject)
HJOBJECT_MEMBER_ACCESS_IMPL(HJTest, HJObject)

//Reflection data for class "HJTestSon", inherited from "HJTest"
struct HJTestSonRegisterHelper_23_16 {
	HJTestSonRegisterHelper_23_16(){
		const std::vector<ReflectInfo> reflectInfoArray{
			MAKE_REFLECT_INFO(age, int, HJTestSon),
			MAKE_REFLECT_INFO(str, std::string, HJTestSon)};
		HJClass::registerClass("HJTestSon", new HJClass("HJTestSon",reflectInfoArray,"HJTest",&HJTestSon::instantiate));
	}
} HJTestSonRegisterHelper_23_16_Instance;
HJOBJECT_GET_CLASS_INFO(HJTestSon, HJTest)
HJOBJECT_MEMBER_ACCESS_IMPL(HJTestSon, HJTest)

